CREATE TABLE TIPO_HABITACION_JMJP(
	ID_TIPO NUMBER(4) CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY,
	DESCRIPCION VARCHAR2(25) CONSTRAINT TIP_HABIT_DESCRIPCION_NN NOT NULL
);

CREATE TABLE HABITACIONES_JMJP(
	ID_HABITACION NUMBER(6) CONSTRAINT HABITACION_PK PRIMARY KEY,
	NOMBRE VARCHAR2(20) CONSTRAINT HABITACION_NOMBRE_NN NOT NULL,
	ID_TIPO NUMBER(4),
	CONSTRAINT TIPO_HABITACION_HABITACION_FK FOREIGN KEY (ID_TIPO) REFERENCES TIPO_HABITACION_JMJP(ID_TIPO)
);

CREATE TABLE CATEGORIAS_JMJP(
	ID_CATEGORIA NUMBER(4) CONSTRAINT CATEGORIA_PK PRIMARY KEY,
	DESCRIPCION VARCHAR2(25),
	IVA NUMBER(3) CONSTRAINT CATEGORIA_IVA_NN NOT NULL
);

CREATE TABLE HOTELES_JMJP(
	ID_HOTEL NUMBER(6) CONSTRAINT HOTEL_PK PRIMARY KEY,
	FECHA_CONSTRUCCION DATE CONSTRAINT HOTEL_FECHA_CONS_NN NOT NULL,
	NOMBRE VARCHAR2(25) CONSTRAINT HOTEL_NOMBRE_NN NOT NULL,
	TELEFONO VARCHAR2(15),
	COLONIA VARCHAR2(30) CONSTRAINT HOTEL_COLONIA_NN NOT NULL,
	CALLE VARCHAR2(30) CONSTRAINT HOTEL_CALLE_NN NOT NULL,
	ID_CATEGORIA NUMBER(4) CONSTRAINT HOTEL_CATEGORIA_NN NOT NULL,
	CONSTRAINT CATEGORIA_HOTEL_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS_JMJP(ID_CATEGORIA)
);

CREATE TABLE HABITACION_HOTEL_JMJP(
	ID_HOTEL NUMBER(6),
	ID_HABITACION NUMBER(6),
	CANTIDAD NUMBER(2) CONSTRAINT HABITACION_HOTEL_CANTI_NN NOT NULL,
	CONSTRAINT HABITACION_HOTEL_PK PRIMARY KEY (ID_HOTEL,ID_HABITACION),
	CONSTRAINT HOTEL_HABIT_HOTEL_FK FOREIGN KEY (ID_HOTEL) REFERENCES HOTELES_JMJP(ID_HOTEL),
	CONSTRAINT HABIT_HABIT_HOTEL_FK FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES_JMJP(ID_HABITACION)
);

CREATE TABLE AGENCIA_JMJP(
	ID_AGENCIA NUMBER(6) CONSTRAINT AGENCIA_PK PRIMARY KEY,
	TELEFONO VARCHAR(15),
	NOMBRE VARCHAR2(25) CONSTRAINT AGENCIA_NOMBRE_NN NOT NULL,
	COLONIA VARCHAR2(30) CONSTRAINT AGENCIA_COLONIA_NN NOT NULL,
	CALLE VARCHAR2(30) CONSTRAINT AGENCIA_CALLE_NN NOT NULL
);

CREATE TABLE EMPLEADO_JMJP(
	ID_EMPLEADO NUMBER(6) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
	TELEFONO VARCHAR(15),
	NOMBRE VARCHAR2(25) CONSTRAINT EMPLEADO_NOMBRE_NN NOT NULL,
	APELLIDO_PATERNO VARCHAR2(25) CONSTRAINT EMPLEADO_APELLIDO_NN NOT NULL,
	APELLIDO_MATERNO VARCHAR2(25)
);

CREATE TABLE AGENCIA_EMPLEADO_JMJP(
	ID_AGENCIA NUMBER(6),
	ID_EMPLEADO NUMBER(6),
	CONSTRAINT AGENCIA_EMPLEADO_PK PRIMARY KEY (ID_AGENCIA, ID_EMPLEADO),
	CONSTRAINT AGENCIA_AG_EMP_FK FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA_JMJP(ID_AGENCIA),
	CONSTRAINT EMPLEADO_AG_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO_JMJP(ID_EMPLEADO)
);

CREATE TABLE CLIENTE_JMJP(
	ID_CLIENTE NUMBER(6) CONSTRAINT CLIENTE_PK PRIMARY KEY,
	NOMBRE VARCHAR2(25) CONSTRAINT CLIENTE_NOMBRE_NN NOT NULL,
	APELLIDO_PATERNO VARCHAR2(25) CONSTRAINT CLIENTE_APELLIDO_NN NOT NULL,
	APELLIDO_MATERNO VARCHAR2(25),
	COLONIA VARCHAR2(30) CONSTRAINT CLIENTE_COLONIA_NN NOT NULL,
	CALLE VARCHAR2(30) CONSTRAINT CLIENTE_CALLE_NN NOT NULL,
	TELEFONO VARCHAR2(15)
);

CREATE TABLE RESERVA_JMJP(
	ID_RESERVA NUMBER(6),
	FECHA_INICIO DATE CONSTRAINT RESERVA_FECHA_INICIO_NN NOT NULL,
	FECHA_FIN DATE,
	PRECIO NUMBER(6,2),
	ID_HOTEL NUMBER(6),
	ID_HABITACION NUMBER(6),
	ID_AGENCIA NUMBER(6),
	ID_EMPLEADO NUMBER(6),
	ID_CLIENTE NUMBER(6),
	CONSTRAINT RESERVA_PK PRIMARY KEY(ID_RESERVA,ID_HOTEL,ID_HABITACION,ID_AGENCIA,ID_EMPLEADO),
	CONSTRAINT HOTEL_HABIT_RESERVA_FK FOREIGN KEY (ID_HOTEL,ID_HABITACION) REFERENCES HABITACION_HOTEL_JMJP(ID_HOTEL,ID_HABITACION),
	CONSTRAINT AGEN_EMP_RESERVA_FK FOREIGN KEY (ID_AGENCIA,ID_EMPLEADO) REFERENCES AGENCIA_EMPLEADO_JMJP(ID_AGENCIA,ID_EMPLEADO),
	CONSTRAINT CLIENTE_RESERVA_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_JMJP(ID_CLIENTE)
);