--a) Insertar 5 registros a cada tabla haciendo uso de las secuencias elaboradas en el Capítulo 11.
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8352','AGENCIA 1','COLONIA 1','CALLE 1');
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8353','AGENCIA 2','COLONIA 2','CALLE 2');
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8354','AGENCIA 3','COLONIA 3','CALLE 3');
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8355','AGENCIA 4','COLONIA 4','CALLE 4');
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8356','AGENCIA 5','COLONIA 5','CALLE 5');
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'463.752.8357','AGENCIA 6','COLONIA 6','CALLE 6');

INSERT INTO EMPLEADO_JMJP VALUES(ID_EMP.NEXTVAL,'543.645.3524','JUAN','GARCIA','FERNANDEZ');
INSERT INTO EMPLEADO_JMJP VALUES(ID_EMP.NEXTVAL,'543.645.3525','ADRIANA','FELIX','TELLEZ');
INSERT INTO EMPLEADO_JMJP VALUES(ID_EMP.NEXTVAL,'543.645.3526','PEDRO','FLORES','HERMOSILLO');
INSERT INTO EMPLEADO_JMJP VALUES(ID_EMP.NEXTVAL,'543.645.3527','MARIA','GARCIA','MEZA');
INSERT INTO EMPLEADO_JMJP VALUES(ID_EMP.NEXTVAL,'543.645.3528','MAURICIO','GONZALEZ','GARCIA');

INSERT INTO AGENCIA_EMPLEADO_JMJP VALUES(100,100);
INSERT INTO AGENCIA_EMPLEADO_JMJP VALUES(101,101);
INSERT INTO AGENCIA_EMPLEADO_JMJP VALUES(102,102);
INSERT INTO AGENCIA_EMPLEADO_JMJP VALUES(103,103);
INSERT INTO AGENCIA_EMPLEADO_JMJP VALUES(104,104);

INSERT INTO CLIENTE_JMJP VALUES(ID_CLI.NEXTVAL,'JAIR','FLORES','PINEDO','C_COL_1','C_CALL_1','654.836.6412');
INSERT INTO CLIENTE_JMJP VALUES(ID_CLI.NEXTVAL,'VANESSA','HERMOSILLO','FLORES','C_COL_2','C_CALL_2','654.836.6413');
INSERT INTO CLIENTE_JMJP VALUES(ID_CLI.NEXTVAL,'JUAN','MENDEZ','GARCIA','C_COL_3','C_CALL_3','654.836.6414');
INSERT INTO CLIENTE_JMJP VALUES(ID_CLI.NEXTVAL,'MARTIN','FELX','HERNANDEZ','C_COL_4','C_CALL_4','654.836.6415');
INSERT INTO CLIENTE_JMJP VALUES(ID_CLI.NEXTVAL,'RAFAEL','SANCHEZ','BONILLA','C_COL_5','C_CALL_5','654.836.6416');

INSERT INTO TIPO_HABITACION_JMJP VALUES(ID_TIP.NEXTVAL,'HABITACION PARA UN HUESPED');
INSERT INTO TIPO_HABITACION_JMJP VALUES(ID_TIP.NEXTVAL,'HABITACION DOBLE PARA UN HUESPED');
INSERT INTO TIPO_HABITACION_JMJP VALUES(ID_TIP.NEXTVAL,'HABITACION DOBLE PARA DOS HUESPEDES');
INSERT INTO TIPO_HABITACION_JMJP VALUES(ID_TIP.NEXTVAL,'HABITACION TRIPLE PARA TRES HUESPEDES');
INSERT INTO TIPO_HABITACION_JMJP VALUES(ID_TIP.NEXTVAL,'HABITACION CUADRUPLE PARA CUATRO HUESPEDES');

INSERT INTO HABITACIONES_JMJP VALUES(ID_HAB.NEXTVAL,'HABITACION INDIVIDUAL',100);
INSERT INTO HABITACIONES_JMJP VALUES(ID_HAB.NEXTVAL,'HABITACION DOBLE INDIV',101);
INSERT INTO HABITACIONES_JMJP VALUES(ID_HAB.NEXTVAL,'HABITACION DOBLE',102);
INSERT INTO HABITACIONES_JMJP VALUES(ID_HAB.NEXTVAL,'HABITACION TRIPLE',103);
INSERT INTO HABITACIONES_JMJP VALUES(ID_HAB.NEXTVAL,'HABITACION CUADRUPLE',104);

INSERT INTO CATEGORIAS_JMJP VALUES(ID_CAT.NEXTVAL,'HOTEL DE CIUDAD',15);
INSERT INTO CATEGORIAS_JMJP VALUES(ID_CAT.NEXTVAL,'HOTEL DE EXPRESS',15);
INSERT INTO CATEGORIAS_JMJP VALUES(ID_CAT.NEXTVAL,'HOTEL DE NEGOCIOS',15);
INSERT INTO CATEGORIAS_JMJP VALUES(ID_CAT.NEXTVAL,'HOTEL DE PLAYA',15);
INSERT INTO CATEGORIAS_JMJP VALUES(ID_CAT.NEXTVAL,'HOTEL DE CARRETERA',15);

INSERT INTO HOTELES_JMJP VALUES(ID_HOT.NEXTVAL,'10/11/12','HOTEL 1','645.745.7645','H_COL_1','H_CALL_1',100);
INSERT INTO HOTELES_JMJP VALUES(ID_HOT.NEXTVAL,'11/11/12','HOTEL 2','645.745.7646','H_COL_2','H_CALL_2',101);
INSERT INTO HOTELES_JMJP VALUES(ID_HOT.NEXTVAL,'12/11/12','HOTEL 3','645.745.7647','H_COL_3','H_CALL_3',102);
INSERT INTO HOTELES_JMJP VALUES(ID_HOT.NEXTVAL,'13/11/12','HOTEL 4','645.745.7648','H_COL_4','H_CALL_4',103);
INSERT INTO HOTELES_JMJP VALUES(ID_HOT.NEXTVAL,'14/11/12','HOTEL 5','645.745.7649','H_COL_5','H_CALL_5',104);

INSERT INTO HABITACION_HOTEL_JMJP VALUES(100,100,1);
INSERT INTO HABITACION_HOTEL_JMJP VALUES(101,101,1);
INSERT INTO HABITACION_HOTEL_JMJP VALUES(102,102,2);
INSERT INTO HABITACION_HOTEL_JMJP VALUES(103,103,3);
INSERT INTO HABITACION_HOTEL_JMJP VALUES(104,104,4);

INSERT INTO RESERVA_JMJP VALUES(ID_RES.NEXTVAL,'15/03/14','16/03/14',732.4,100,100,100,100,100);
INSERT INTO RESERVA_JMJP VALUES(ID_RES.NEXTVAL,'17/04/15','18/04/15',1732.4,101,101,101,101,101);
INSERT INTO RESERVA_JMJP VALUES(ID_RES.NEXTVAL,'19/05/16','20/05/16',2732.4,102,102,102,102,102);
INSERT INTO RESERVA_JMJP VALUES(ID_RES.NEXTVAL,'21/06/17','22/06/17',3732.4,103,103,103,103,103);
INSERT INTO RESERVA_JMJP VALUES(ID_RES.NEXTVAL,'23/07/18','24/07/18',4732.4,104,104,104,104,104);

--b) Escribir las sentencias SELECT para observar el comportamiento de los datos insertados en el punto 2.
SELECT * FROM AGENCIA_JMJP;
SELECT * FROM EMPLEADO_JMJP;
SELECT * FROM AGENCIA_EMPLEADO_JMJP;
SELECT * FROM CLIENTE_JMJP;
SELECT * FROM TIPO_HABITACION_JMJP;
SELECT * FROM HABITACIONES_JMJP;
SELECT * FROM CATEGORIAS_JMJP;
SELECT * FROM HOTELES_JMJP;
SELECT * FROM HABITACION_HOTEL_JMJP;
SELECT * FROM RESERVA_JMJP;

--c) Ejecutar la sentencia COMMIT para que las inserciones queden de forma permanente en la Base de Datos.
COMMIT;

--d) Ejecutar 5 sentencias UPDATE para modificar datos a su criterio.
UPDATE AGENCIA_JMJP SET TELEFONO = '642.643.654';
UPDATE EMPLEADO_JMJP SET APELLIDO_MATERNO = 'JARA';
UPDATE CLIENTE_JMJP SET NOMBRE = 'KEVIN';
UPDATE TIPO_HABITACION_JMJP SET DESCRIPCION = 'HABITACION PARA UN SOLO HUESPED';
UPDATE CATEGORIAS_JMJP SET DESCRIPCION = 'HOTEL EXPRESS';

--e) Ejecutar 5 sentencias DELETE para eliminar datos a su criterio.
DELETE AGENCIA_EMPLEADO_JMJP WHERE ID_AGENCIA = 100;
DELETE AGENCIA_JMJP WHERE ID_AGENCIA = 100;
DELETE HABITACION_HOTEL_JMJP WHERE ID_HOTEL = 101;
DELETE HOTELES_JMJP WHERE ID_HOTEL = 101;
DELETE CATEGORIAS_JMJP WHERE ID_CATEGORIA = 101;

--f) Elaborar las sentencias necesarias sobre el control de transacciones, haciendo uso de la siguiente estructura:
--1
SELECT * FROM AGENCIA_JMJP;
UPDATE AGENCIA_JMJP SET NOMBRE = 'AGENCIA 6' WHERE ID_AGENCIA = 106;
SELECT * FROM AGENCIA_JMJP;
DELETE AGENCIA_JMJP WHERE ID_AGENCIA = 106;
COMMIT;

--2
SELECT * FROM AGENCIA_JMJP;
UPDATE AGENCIA_JMJP SET TELEFONO = '462.745.6352' WHERE ID_AGENCIA = 105;
SELECT * FROM AGENCIA_JMJP;
SAVEPOINT S1;
DELETE AGENCIA_JMJP WHERE ID_AGENCIA = 105;
SELECT * FROM AGENCIA_JMJP;
SAVEPOINT S2;
INSERT INTO AGENCIA_JMJP VALUES(ID_AG.NEXTVAL,'764.643.2345','AGENCIA 16','COLONIA 16','CALLE 16');
SELECT * FROM AGENCIA_JMJP;
ROLLBACK S1;
SELECT * FROM AGENCIA_JMJP;
ROLLBACK;
SELECT * FROM AGENCIA_JMJP;

--3
SELECT * FROM AGENCIA_JMJP;
UPDATE AGENCIA_JMJP SET NOMBRE = 'AGENCIA' WHERE ID_AGENCIA = 108;
SELECT * FROM AGENCIA_JMJP;
SELECT * FROM HOTEL_2021.AGENCIA_JMJP;--OTRO USUARIO
COMMIT;
SELECT * FROM HOTEL_2021.AGENCIA_JMJP;--OTRO USUARIO

--4
SELECT * FROM AGENCIA_JMJP;
UPDATE AGENCIA_JMJP SET COLONIA = 'ZAPATA' WHERE ID_AGENCIA = 110;
SELECT * FROM AGENCIA_JMJP;
SELECT * FROM HOTEL_2021.AGENCIA_JMJP; --OTRO USUARIO
UPDATE HOTEL_2021.AGENCIA_JMJP SET COLONIA = 'COLONIAAA' WHERE ID_AGENCIA = 110; --OTRO USUARIO
COMMIT;
SELECT * FROM AGENCIA_JMJP;
COMMIT; --OTRO USUARIO
SELECT * FROM AGENCIA_JMJP;  SELECT * FROM HOTEL_2021.AGENCIA_JMJP; --OTRO USUARIO

--5
SELECT * FROM AGENCIA_JMJP;
UPDATE AGENCIA_JMJP SET CALLE = 'CALL 1' WHERE ID_AGENCIA = 112;
SELECT * FROM AGENCIA_JMJP;
DELETE AGENCIA_JMJP WHERE ID_AGENCIA = 112;
SELECT * FROM AGENCIA_JMJP;
CREATE TABLE X(COL1 VARCHAR2(5));
ROLLBACK;
SELECT * FROM X;
SELECT * FROM AGENCIA_JMJP;