--a) Pasar los datos de las 7 tablas del esquema HR al esquema RH.
INSERT INTO REGIONES_JMJP SELECT * FROM HR.REGIONS;
INSERT INTO PAISES_JMJP SELECT * FROM HR.COUNTRIES;
INSERT INTO UBICACIONES_JMJP SELECT * FROM HR.LOCATIONS;
INSERT INTO DEPARTAMENTOS_JMJP(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO,ID_UBICACION) SELECT DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID FROM HR.DEPARTMENTS;
INSERT INTO TRABAJADORES_JMJP SELECT * FROM HR.EMPLOYEES;
UPDATE DEPARTAMENTOS_JMJP SET ID_GERENTE = (SELECT MANAGER_ID FROM HR.DEPARTMENTS 
    WHERE MANAGER_ID IS NOT NULL AND ID_DEPARTAMENTO = HR.DEPARTMENTS.DEPARTMENT_ID);
INSERT INTO TRABAJOS_JMJP SELECT * FROM HR.JOBS;
INSERT INTO HISTORIA_LABORAL_JMJP SELECT * FROM HR.JOB_HISTORY;


--b) Insertar 5 registros a cada tabla de RH haciendo uso de las secuencias elaboradas en el Capítulo 11.
INSERT INTO REGIONES_JMJP VALUES(REG_ID.NEXTVAL,'AMERICA DEL NORTE');
INSERT INTO REGIONES_JMJP VALUES(REG_ID.NEXTVAL,'AMERICA DEL SUR');
INSERT INTO REGIONES_JMJP VALUES(REG_ID.NEXTVAL,'EUROPA');
INSERT INTO REGIONES_JMJP VALUES(REG_ID.NEXTVAL,'AFRICA');
INSERT INTO REGIONES_JMJP VALUES(REG_ID.NEXTVAL,'ASIA');

INSERT INTO UBICACIONES_JMJP VALUES(UBI_ID.NEXTVAL,'Corps-Saints',6437,'LONDON',NULL,'UK');
INSERT INTO UBICACIONES_JMJP VALUES(UBI_ID.NEXTVAL,'Corps-Saints 2',6438,'LONDON',NULL,'UK');
INSERT INTO UBICACIONES_JMJP VALUES(UBI_ID.NEXTVAL,'Corps-Saints 3',6439,'LONDON',NULL,'UK');
INSERT INTO UBICACIONES_JMJP VALUES(UBI_ID.NEXTVAL,'Corps-Saints 4',6440,'LONDON',NULL,'UK');
INSERT INTO UBICACIONES_JMJP VALUES(UBI_ID.NEXTVAL,'Corps-Saints 5',6441,'LONDON',NULL,'UK');
INSERT INTO UBICACIONES_JMJP VALUES(1,'ISHDBVN','35323','DFSVSDV','SDJVNSDASD',NULL);

INSERT INTO DEPARTAMENTOS_JMJP VALUES(DEP_ID.NEXTVAL,'DEPARTAMENTO 1',NULL,3300);
INSERT INTO DEPARTAMENTOS_JMJP VALUES(DEP_ID.NEXTVAL,'DEPARTAMENTO 2',NULL,3400);
INSERT INTO DEPARTAMENTOS_JMJP VALUES(DEP_ID.NEXTVAL,'DEPARTAMENTO 3',NULL,3500);
INSERT INTO DEPARTAMENTOS_JMJP VALUES(DEP_ID.NEXTVAL,'DEPARTAMENTO 4',NULL,3600);
INSERT INTO DEPARTAMENTOS_JMJP VALUES(DEP_ID.NEXTVAL,'DEPARTAMENTO 5',NULL,3700);

INSERT INTO TRABAJADORES_JMJP VALUES(EMP_ID.NEXTVAL,'JUAN','GONZALEZ','JUAN@GMAIL.COM','543.764.4325','12/12/12',NULL,6523,NULL,NULL,280); 
INSERT INTO TRABAJADORES_JMJP VALUES(EMP_ID.NEXTVAL,'JOEL','PEREZ','JOEL@GMAIL.COM','543.764.4326','12/12/12',NULL,6523,NULL,NULL,290);
INSERT INTO TRABAJADORES_JMJP VALUES(EMP_ID.NEXTVAL,'LUCIA','FERNANDEZ','LUCIA@GMAIL.COM','543.764.4327','12/12/12',NULL,6523,NULL,NULL,300);
INSERT INTO TRABAJADORES_JMJP VALUES(EMP_ID.NEXTVAL,'MARIANO','TELLEZ','MARIANO@GMAIL.COM','543.764.4328','12/12/12',NULL,6523,NULL,NULL,310);
INSERT INTO TRABAJADORES_JMJP VALUES(EMP_ID.NEXTVAL,'PEDRO','BELTRAN','PEDRO@GMAIL.COM','543.764.4329','12/12/12',NULL,6523,NULL,NULL,320);


--c) Escribir las sentencias SELECT para observar el comportamiento de los datos insertados en el punto 2.
SELECT * FROM REGIONES_JMJP;
SELECT * FROM UBICACIONES_JMJP;
SELECT * FROM DEPARTAMENTOS_JMJP;
SELECT * FROM TRABAJADORES_JMJP;


--d) Ejecutar la sentencia COMMIT para que las inserciones queden de forma permanente en la Base de Datos.
COMMIT;


--e) Ejecutar 5 sentencias UPDATE para modificar datos a su criterio en el esquema RH.
UPDATE REGIONES_JMJP SET NOMBRE_REGION = 'AMERICA' WHERE ID_REGION = 5;
UPDATE UBICACIONES_JMJP SET DIRECCION = 'Corps-Saints 1' WHERE ID_UBICACION = 3300;
UPDATE DEPARTAMENTOS_JMJP SET NOMBRE_DEPARTAMENTO = 'DEPARTAMENTO 6' WHERE ID_DEPARTAMENTO = 300;
UPDATE TRABAJADORES_JMJP SET NOMBRE = 'ALONSO' WHERE ID_TRABAJADOR = 206;
UPDATE TRABAJADORES_JMJP SET APELLIDO = 'ALONSO' WHERE ID_TRABAJADOR = 208;


--f) Ejecutar 5 sentencias DELETE para eliminar datos a su criterio en el esquema RH.
DELETE FROM REGIONES_JMJP WHERE ID_REGION = 5;
DELETE FROM UBICACIONES_JMJP WHERE ID_UBICACION = 3300;
DELETE FROM DEPARTAMENTOS_JMJP WHERE ID_DEPARTAMENTO = 300;
DELETE FROM TRABAJADORES_JMJP WHERE ID_TRABAJADOR = 206;
DELETE FROM TRABAJADORES_JMJP WHERE ID_TRABAJADOR = 208;


--g) Elaborar las sentencias necesarias sobre el control de transacciones, haciendo uso de la siguiente estructura:
--1:
SELECT * FROM REGIONES_JMJP;
UPDATE REGIONES_JMJP SET NOMBRE_REGION = 'AMERICA' WHERE ID_REGION = 5;
SELECT * FROM REGIONES_JMJP;
DELETE REGIONES_JMJP WHERE ID_REGION = 5;
COMMIT;

--2
SELECT * FROM UBICACIONES_JMJP;
UPDATE UBICACIONES_JMJP SET DIRECCION = 'Corps-Saints 1' WHERE ID_UBICACION = 3300;
SELECT * FROM UBICACIONES_JMJP;
SAVEPOINT S1;
DELETE UBICACIONES_JMJP WHERE ID_UBICACION = 1;
SELECT * FROM UBICACIONES_JMJP;
SAVEPOINT S2;
INSERT INTO UBICACIONES_JMJP VALUES(2,'3DVSR','RGSDG','SGSGSGGSG','SGDSGSDV',NULL);
SELECT * FROM UBICACIONES_JMJP;
ROLLBACK S1;
SELECT * FROM UBICACIONES_JMJP;
ROLLBACK;
SELECT * FROM UBICACIONES_JMJP;

--3
SELECT * FROM TRABAJOS_JMJP;
UPDATE TRABAJOS_JMJP SET NOMBRE_TRABAJO = 'JHSFHIDUOAJN' WHERE ID_TRABAJO = 'vw32';
SELECT * FROM TRABAJOS_JMJP;
SELECT * FROM RH.TRABAJOS_JMJP;--OTRO USUARIO
COMMIT;
SELECT * FROM RH.TRABAJOS_JMJP;--OTRO USUARIO

--4
SELECT * FROM PAISES_JMJP;
UPDATE PAISES_JMJP SET NOMBRE_PAIS = 'MEXICO' WHERE ID_PAIS = 'MX';
SELECT * FROM PAISES_JMJP;
SELECT * FROM RH.PAISES_JMJP; --OTRO USUARIO
UPDATE RH.PAISES_JMJP SET NOMBRE_PAIS = 'MEXICOO' WHERE ID_PAIS = 'MX'; --OTRO USUARIO
COMMIT;
SELECT * FROM PAISES_JMJP;
COMMIT; --OTRO USUARIO
SELECT * FROM PAISES_JMJP;  SELECT * FROM RH.PAISES_JMJP; --OTRO USUARIO

--5
SELECT * FROM REGIONES_JMJP;
UPDATE REGIONES_JMJP SET NOMBRE_REGION = 'AMERICA' WHERE ID_REGION = 6;
SELECT * FROM REGIONES_JMJP;
DELETE REGIONES_JMJP WHERE ID_REGION = 6;
SELECT * FROM REGIONES_JMJP;
CREATE TABLE X(COL1 VARCHAR2(5));
ROLLBACK;
SELECT * FROM X;
SELECT * FROM REGIONES_JMJP;
