--1. Expresiones
SELECT ID_RESERVA,FECHA_INICIO,FECHA_FIN,PRECIO,(PRECIO*2)DOBLE_PRECIO FROM RESERVA_JMJP; 
SELECT ID_RESERVA,FECHA_INICIO,FECHA_FIN,PRECIO,(PRECIO-((PRECIO*15)/100))"MENOS 15%" FROM RESERVA_JMJP;
SELECT ID_RESERVA,FECHA_INICIO,FECHA_FIN,PRECIO,(PRECIO+((PRECIO*15)/100))"MAS 15%" FROM RESERVA_JMJP;

--2. Concatenación
SELECT NOMBRE||' '||APELLIDO_PATERNO||' '||APELLIDO_MATERNO CLIENTE FROM CLIENTE_JMJP;
SELECT NOMBRE||' '||APELLIDO_PATERNO||' '||APELLIDO_MATERNO||', TEL:'||TELEFONO CLIENTE FROM EMPLEADO_JMJP;
SELECT 'INICIO: '||FECHA_INICIO||',FIN:'||FECHA_FIN||', PRECIO:'||PRECIO||', HOTEL:'||ID_HOTEL ||', HABITACION:'||ID_HABITACION RESERVA FROM RESERVA_JMJP R;

--3. Concatenación con valor literal
SELECT 'EL HOTEL '||NOMBRE||' FUE CONSTRUIDO EN '||FECHA_CONSTRUCCION||' Y TIENE LA CATEGORIA '||ID_CATEGORIA HOTEL FROM HOTELES_JMJP;
SELECT 'EL CLIENTE '||ID_CLIENTE||' INGRESO AL HOTEL '||ID_HOTEL||' LA FECHA '||FECHA_INICIO||' Y SALIO LA FECHA '||FECHA_FIN RESERVA FROM RESERVA_JMJP;
SELECT 'EL EMPLEADO '||ID_EMPLEADO||' ESTA EN LA AGENCIA '||ID_AGENCIA AGENCIA_EMPLEADO FROM AGENCIA_EMPLEADO_JMJP;

--4. Operador Q
SELECT q'[EL HOTEL ']'||NOMBRE||q'[' FUE CONSTRUIDO EN ']'||FECHA_CONSTRUCCION||q'[' Y TIENE LA CATEGORIA ']'||ID_CATEGORIA||q'[']' HOTEL FROM HOTELES_JMJP;
SELECT q'[EL CLIENTE ']'||ID_CLIENTE||q'[' INGRESO AL HOTEL ']'||ID_HOTEL||q'[' LA FECHA ']'||FECHA_INICIO||q'[' Y SALIO LA FECHA ']'||FECHA_FIN||q'[']' RESERVA FROM RESERVA_JMJP;
SELECT q'[EL EMPLEADO ']'||ID_EMPLEADO||q'[' ESTA EN LA AGENCIA ']'||ID_AGENCIA||q'[']' AGENCIA_EMPLEADO FROM AGENCIA_EMPLEADO_JMJP;

--5. Alias (para cada tipo)
SELECT ID_CATEGORIA AS ID, DESCRIPCION AS "Descripcion", IVA "iva" FROM CATEGORIAS_JMJP;
SELECT ID_EMPLEADO AS ID, NOMBRE||' '||APELLIDO_PATERNO||' '||APELLIDO_MATERNO AS "Nombre Completo", TELEFONO AS TEL FROM EMPLEADO_JMJP;
SELECT ID_RESERVA AS ID, FECHA_INICIO AS "Fecha de Ingreso", FECHA_FIN "Fecha de Salida",PRECIO costo_reserva FROM RESERVA_JMJP;

--6. Distinct
SELECT DISTINCT NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO FROM CLIENTE_JMJP;
SELECT DISTINCT FECHA_CONSTRUCCION,NOMBRE,TELEFONO,COLONIA FROM HOTELES_JMJP;
SELECT DISTINCT NOMBRE,ID_TIPO FROM HABITACIONES_JMJP;



