--= Y <>
SELECT * FROM AGENCIA_JMJP WHERE NOMBRE = 'AGENCIA 5';
SELECT * FROM AGENCIA_JMJP WHERE COLONIA <> 'COLONIA 6';
SELECT * FROM CATEGORIAS_JMJP WHERE IVA = 15;
SELECT * FROM CATEGORIAS_JMJP WHERE DESCRIPCION <> 'HOTEL DE PLAYA';
SELECT * FROM HOTELES_JMJP WHERE ID_CATEGORIA = 103;
SELECT * FROM HOTELES_JMJP WHERE FECHA_CONSTRUCCION <> '12/11/12';

--> Y <
SELECT * FROM HABITACION_HOTEL_JMJP WHERE CANTIDAD > 1;
SELECT * FROM HABITACION_HOTEL_JMJP WHERE CANTIDAD < 4;
SELECT * FROM HABITACIONES_JMJP WHERE ID_TIPO > 101;
SELECT * FROM HABITACIONES_JMJP WHERE ID_HABITACION < 103;
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO > 101;
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO < 105;

-->= Y <=
SELECT * FROM HABITACION_HOTEL_JMJP WHERE CANTIDAD >= 2;
SELECT * FROM HABITACION_HOTEL_JMJP WHERE CANTIDAD <= 3;
SELECT * FROM HABITACIONES_JMJP WHERE ID_TIPO >= 101;
SELECT * FROM HABITACIONES_JMJP WHERE ID_HABITACION <= 103;
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO >= 100;
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO <= 105;

--Between y not between
SELECT * FROM CLIENTE_JMJP WHERE (ID_CLIENTE BETWEEN 102 AND 104);
SELECT * FROM CLIENTE_JMJP WHERE (ID_CLIENTE NOT BETWEEN 102 AND 103);
SELECT * FROM HOTELES_JMJP WHERE (FECHA_CONSTRUCCION BETWEEN '10/11/12' AND '13/11/12');
SELECT * FROM HOTELES_JMJP WHERE (FECHA_CONSTRUCCION NOT BETWEEN '11/11/12' AND '12/11/12');
SELECT * FROM RESERVA_JMJP WHERE (PRECIO BETWEEN 1000 AND 5000);
SELECT * FROM RESERVA_JMJP WHERE (PRECIO NOT BETWEEN 2500 AND 3500);

--In y not in
SELECT * FROM TIPO_HABITACION_JMJP WHERE ID_TIPO IN (SELECT ID_TIPO FROM TIPO_HABITACION_JMJP WHERE ID_TIPO NOT IN (101,103));
SELECT * FROM CLIENTE_JMJP WHERE ID_CLIENTE IN (SELECT ID_CLIENTE FROM CLIENTE_JMJP WHERE ID_CLIENTE NOT IN (100,102,104));
SELECT * FROM RESERVA_JMJP WHERE ID_RESERVA IN (SELECT ID_RESERVA FROM RESERVA_JMJP WHERE ID_RESERVA NOT IN (101,102));

--Like y not like (usar en al menos 1 consulta, ESCAPE)
SELECT * FROM TIPO_HABITACION_JMJP WHERE DESCRIPCION LIKE '%UN%';
SELECT * FROM TIPO_HABITACION_JMJP WHERE DESCRIPCION NOT LIKE '%HUESPED';
SELECT * FROM EMPLEADO_JMJP WHERE NOMBRE LIKE '_A%';
SELECT * FROM EMPLEADO_JMJP WHERE NOMBRE NOT LIKE '%C%';
SELECT * FROM HOTELES_JMJP WHERE TELEFONO LIKE '%8';
SELECT * FROM HOTELES_JMJP WHERE COLONIA NOT LIKE '%3';

--Is null e is not null
SELECT * FROM RESERVA_JMJP WHERE ID_CLIENTE IS NULL;
SELECT * FROM RESERVA_JMJP WHERE ID_EMPLEADO IS NOT NULL;
SELECT * FROM CLIENTE_JMJP WHERE TELEFONO IS NULL;
SELECT * FROM CATEGORIAS_JMJP WHERE DESCRIPCION IS NOT NULL;
SELECT * FROM AGENCIA_JMJP WHERE CALLE IS NULL;
SELECT * FROM HOTELES_JMJP WHERE TELEFONO IS NOT NULL;

--AND
SELECT * FROM CLIENTE_JMJP WHERE ID_CLIENTE > 100 AND ID_CLIENTE < 104;
SELECT * FROM HOTELES_JMJP WHERE FECHA_CONSTRUCCION > '11/11/12' AND NOMBRE <> 'HOTEL 5';
SELECT * FROM HABITACIONES_JMJP WHERE ID_TIPO IS NOT NULL AND ID_HABITACION >= 103;

--OR
SELECT * FROM CLIENTE_JMJP WHERE ID_CLIENTE > 100 OR ID_CLIENTE < 104;
SELECT * FROM HOTELES_JMJP WHERE FECHA_CONSTRUCCION > '11/11/12' OR NOMBRE <> 'HOTEL 5';
SELECT * FROM HABITACIONES_JMJP WHERE ID_TIPO IS NOT NULL OR ID_HABITACION >= 103;

--Uso de paréntesis
SELECT ID_EMPLEADO,TELEFONO,(NOMBRE||' '||APELLIDO_PATERNO||' '||APELLIDO_MATERNO) AS NOMBRE_COMPLETO FROM EMPLEADO_JMJP;
SELECT ID_HOTEL,ID_HABITACION,CANTIDAD,(CANTIDAD*2) AS DOBLE FROM HABITACION_HOTEL_JMJP;
SELECT * FROM AGENCIA_JMJP WHERE (ID_AGENCIA BETWEEN 102 AND 104) OR (CALLE = 'CALLE 1');

--Precedencia de operadores
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO = 100 OR ID_EMPLEADO = 103 AND NOMBRE = 'MARIA'; 
SELECT * FROM EMPLEADO_JMJP WHERE (ID_EMPLEADO = 100 OR ID_EMPLEADO = 103) AND NOMBRE = 'MARIA'; 
SELECT * FROM EMPLEADO_JMJP WHERE ID_EMPLEADO = 100 OR (ID_EMPLEADO = 103 AND NOMBRE = 'MARIA'); 

--Order by
SELECT * FROM HABITACION_HOTEL_JMJP ORDER BY CANTIDAD;
SELECT * FROM EMPLEADO_JMJP ORDER BY APELLIDO_PATERNO;
SELECT * FROM RESERVA_JMJP ORDER BY FECHA_FIN DESC;

--Variables de sustitución con &
SELECT * FROM CLIENTE_JMJP WHERE NOMBRE = '&NOMBRE_CLIENTE';
SELECT * FROM HOTELES_JMJP WHERE ID_CATEGORIA = '&ID_CATEGORIA';
SELECT * FROM TIPO_HABITACION_JMJP WHERE DESCRIPCION LIKE '%&DESC_CONTIENE%';

--Variables de sustitución con &&
SELECT 'EL CLIENTE &&NOMBRE_CLIENTE TIENE EL ID: '||ID_CLIENTE AS SALIDA FROM CLIENTE_JMJP WHERE NOMBRE = '&NOMBRE_CLIENTE';
SELECT 'EL NOMBRE DEL HOTEL CON EL ID_CATEGORIA: &&ID_CATEGORIA ES:'||NOMBRE AS SALIDA FROM HOTELES_JMJP WHERE ID_CATEGORIA = '&ID_CATEGORIA';
SELECT 'EL TIPO DE HABITACION '||ID_TIPO||' CONTIENE ''&&DESC_CONTIENE'' EN SU DESCRIPCION' AS SALIDA FROM TIPO_HABITACION_JMJP WHERE DESCRIPCION LIKE '%&DESC_CONTIENE%';

--Define y undefine
DEFINE CANT = 3;
SELECT * FROM HABITACION_HOTEL_JMJP WHERE CANTIDAD = &CANT;
UNDEFINE CANT;

DEFINE NOM = 'ADRIANA';
SELECT * FROM EMPLEADO_JMJP WHERE NOMBRE = '&NOM';
UNDEFINE NOM;

DEFINE FECHA = '12/11/12';
SELECT * FROM HOTELES_JMJP WHERE FECHA_CONSTRUCCION >= '&FECHA';
UNDEFINE FECHA;


