--INSERCIONES EN LA TABLA CINES
INSERT INTO CINES_JMJP VALUES(CID.NEXTVAL,'CINE 1','MANUEL FERNANDEZ','GALERIAS ZACATECAS, ZAC.','645.635.5612');
INSERT INTO CINES_JMJP VALUES(CID.NEXTVAL,'CINE 2','ANGEL GALLEGOS','COL. CENTRO, #123 ZACATECAS, ZAC.','654.192.5463');
INSERT INTO CINES_JMJP VALUES(CID.NEXTVAL,'CINE 3','PERLA MARTINEZ','COL. CENTRO #270 GUADALUPE, ZAC.','873.123.1234');
INSERT INTO CINES_JMJP VALUES(CID.NEXTVAL,'CINE 4','GABRIEL PEREZ','COL. ALAMEDA #175 JEREZ, ZAC.','098.789.4501');
INSERT INTO CINES_JMJP VALUES(CID.NEXTVAL,'CINE 5','PASCUAL BARRIOS','COL. LOMAS #222 VALPARAISO, ZAC.','643.145.7592');

--INSERCIONES EN LA TABLA CLASIFICACIONES
INSERT INTO CLASIFICACIONES_JMJP VALUES('AA','PELICULAS PARA TODO PUBLICO CON ATRACTIVO INFANTIL.');
INSERT INTO CLASIFICACIONES_JMJP VALUES('A','PELICULAS PARA TODO PUBLICO.');
INSERT INTO CLASIFICACIONES_JMJP VALUES('B','PELICULAS PARA ADOLECENTES DE 12 AÑOS EN ADELANTE.');
INSERT INTO CLASIFICACIONES_JMJP VALUES('B15','PELICULAS NO RECOMENDADAS PARA MENORES DE 15 AÑOS.');
INSERT INTO CLASIFICACIONES_JMJP VALUES('C','PELICULAS PARA ADULTOS DE 18 AÑOS EN ADELANTE.');

--INSERCIONES EN LA TABLA CATEGORIAS
INSERT INTO CATEGORIAS_JMJP VALUES(CATID.NEXTVAL,'ACCION','ALTA DOSIS DE ADRENALINA CON UNA BUENA CARGA DE ACROBACIAS, PELEAS, ETC');
INSERT INTO CATEGORIAS_JMJP VALUES(CATID.NEXTVAL,'CIENCIA FICCION','BASADOS EN FENOMENOS IMAGINARIOS.');
INSERT INTO CATEGORIAS_JMJP VALUES(CATID.NEXTVAL,'COMEDIA','DISEÑADAS PARA PROVOCAR LA RISA O LA ALEGRIA ENTRE LOS ESPECTADORES.');
INSERT INTO CATEGORIAS_JMJP VALUES(CATID.NEXTVAL,'DRAMA','CENTRADAS EN DESARROLLAR PROBLEMAS ENTRE LOS DIFERENTES PROTAGONISTAS.');
INSERT INTO CATEGORIAS_JMJP VALUES(CATID.NEXTVAL,'TERROR','SU PRINCIPAL OBJETIVO ES CAUSAR MIEDO, HORROR, INCOMODIDAD O PREOCUPACIÓN.');

--INSERCIONES EN LA TABLA PELICULAS
INSERT INTO PELICULAS_JMJP VALUES(PELID.nextval,'SOUL',101.38,'AA');
INSERT INTO PELICULAS_JMJP VALUES(PELID.nextval,'GODZILLA VS KONG',113.09,'B');
INSERT INTO PELICULAS_JMJP VALUES(PELID.nextval,'HALLOWEEN KILLS',105.12,'C');
INSERT INTO PELICULAS_JMJP VALUES(PELID.nextval,'DUNE',155.13,'B15');
INSERT INTO PELICULAS_JMJP VALUES(PELID.nextval,'DEADPOOL',108.06,'C');

--INSERCIONES EN LA TABLA PELICULA_CATEGORIAS
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(10,12);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(11,10);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(11,11);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(12,14);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(12,10);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(13,11);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(13,10);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(13,13);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(14,10);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(14,11);
INSERT INTO PELICULA_CATEGORIAS_JMJP VALUES(14,12);

--INSERCIONES EN LA TABLA PROYECCIONES
INSERT INTO PROYECCIONES_JMJP VALUES(PROYID.NEXTVAL,10,10,'12/05/20','12/06/20');
INSERT INTO PROYECCIONES_JMJP VALUES(PROYID.NEXTVAL,11,11,'01/08/21','03/10/21');
INSERT INTO PROYECCIONES_JMJP VALUES(PROYID.NEXTVAL,12,12,'24/11/20','25/12/20');
INSERT INTO PROYECCIONES_JMJP VALUES(PROYID.NEXTVAL,13,13,'09/09/21','10/10/21');
INSERT INTO PROYECCIONES_JMJP VALUES(PROYID.NEXTVAL,14,14,'20/12/20','23/01/21');

--INSERCIONES EN LA TABLA CLIENTES
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'JUAN PEREZ',20);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'MARIA FLORES',15);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'PEDRO ROBLES',10);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'ADRIAN MONTELLANO',25);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'MARTIN LOPEZ',30);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'JOEL MARTINEZ',23);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'FERNANDO OLIVEROS',14);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'GUADALUPE SUAREZ',26);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'ROBERTO OVALLE',18);
INSERT INTO CLIENTES_JMJP VALUES(CLID.NEXTVAL,'SAUL MARTINEZ',44);

--INSERCIONES EN LA TABLA REF PAGOS
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,123.50,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,345,'TARJETA DE CREDITO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,235,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,768.50,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,200.50,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,432,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,543,'TARJETA DE CREDITO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,654,'TARJETA DE CREDITO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,199.50,'EFECTIVO');
INSERT INTO REF_PAGOS_JMJP VALUES(RPID.NEXTVAL,222.50,'EFECTIVO');

--INSERCIONES EN LA TABLA SALAS
INSERT INTO SALAS_JMJP VALUES(SALID.NEXTVAL,'1-A',40);
INSERT INTO SALAS_JMJP VALUES(SALID.NEXTVAL,'2-B',35);
INSERT INTO SALAS_JMJP VALUES(SALID.NEXTVAL,'3-C',30);
INSERT INTO SALAS_JMJP VALUES(SALID.NEXTVAL,'4-D',38);
INSERT INTO SALAS_JMJP VALUES(SALID.NEXTVAL,'5-E',33);

--INSERCIONES EN LA TABLA FUNCIONES
INSERT INTO FUNCIONES_JMJP VALUES(FUNID.NEXTVAL,TO_DATE('10/05/20 06:45 PM','DD/MM/YY HH:MI PM'),TO_DATE('10/05/20 08:45 PM','DD/MM/YY HH:MI PM'));
INSERT INTO FUNCIONES_JMJP VALUES(FUNID.NEXTVAL,TO_DATE('11/09/21 07:45 PM','DD/MM/YY HH:MI PM'),TO_DATE('11/09/21 09:45 PM','DD/MM/YY HH:MI PM'));
INSERT INTO FUNCIONES_JMJP VALUES(FUNID.NEXTVAL,TO_DATE('12/12/20 08:45 PM','DD/MM/YY HH:MI PM'),TO_DATE('12/12/20 10:45 PM','DD/MM/YY HH:MI PM'));
INSERT INTO FUNCIONES_JMJP VALUES(FUNID.NEXTVAL,TO_DATE('03/10/21 09:45 PM','DD/MM/YY HH:MI PM'),TO_DATE('03/10/21 11:45 PM','DD/MM/YY HH:MI PM'));
INSERT INTO FUNCIONES_JMJP VALUES(FUNID.NEXTVAL,TO_DATE('28/12/20 10:45 PM','DD/MM/YY HH:MI PM'),TO_DATE('28/12/20 12:45 AM','DD/MM/YY HH:MI PM'));

--INSERCIONES EN LA TABLA ENTRADAS
INSERT INTO ENTRADAS_JMJP VALUES('3F',10,10,10,10,10);
INSERT INTO ENTRADAS_JMJP VALUES('2C',11,11,10,10,10);
INSERT INTO ENTRADAS_JMJP VALUES('1B',12,12,11,11,11);
INSERT INTO ENTRADAS_JMJP VALUES('8A',13,13,11,11,11);
INSERT INTO ENTRADAS_JMJP VALUES('5A',14,14,12,12,12);
INSERT INTO ENTRADAS_JMJP VALUES('3C',15,15,12,12,12);
INSERT INTO ENTRADAS_JMJP VALUES('5D',16,16,13,13,13);
INSERT INTO ENTRADAS_JMJP VALUES('8F',17,17,13,13,13);
INSERT INTO ENTRADAS_JMJP VALUES('6E',18,18,14,14,14);
INSERT INTO ENTRADAS_JMJP VALUES('2D',19,19,14,14,14);

COMMIT;