CREATE TABLE CINES_JMJP(
    CINE_ID NUMBER CONSTRAINT CINES_PK PRIMARY KEY,
    NOMBRE_CINE VARCHAR2(25) CONSTRAINT NOMBRE_CINE_NN NOT NULL,
    GERENTE VARCHAR2(50),
    DIRECCION VARCHAR2(100) CONSTRAINT DIRECCION_CINE_NN NOT NULL,
    NUM_TEL VARCHAR2(15)
);

CREATE TABLE CLASIFICACIONES_JMJP(
    CLASIFICACION_ID CHAR(3) CONSTRAINT CLASIFICACION_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(100)
);

CREATE TABLE CATEGORIAS_JMJP(
    CATEGORIA_ID NUMBER(2) CONSTRAINT CATEGORIA_PK PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(25) CONSTRAINT NOMBRE_CATEGORIA_NN NOT NULL,
    DESCRIPCION VARCHAR(75)
);

CREATE TABLE PELICULAS_JMJP(
    PELICULA_ID NUMBER CONSTRAINT PELICULA_PK PRIMARY KEY,
    NOMBRE_PELICULA VARCHAR2(30) CONSTRAINT NOMBRE_PELICULA_NN NOT NULL,
    DURACION NUMBER(6,2),
    CLASIFICACION_ID CHAR(3) CONSTRAINT CLASIFICACION_PELICULA_NN NOT NULL,
    CONSTRAINT CLASIFICACION_PELICULA_FK FOREIGN KEY (CLASIFICACION_ID) REFERENCES CLASIFICACIONES_JMJP(CLASIFICACION_ID)
);

CREATE TABLE PELICULA_CATEGORIAS_JMJP(
    PELICULA_ID NUMBER,
    CATEGORIA_ID NUMBER,
    CONSTRAINT PELI_CAT_PK PRIMARY KEY (PELICULA_ID,CATEGORIA_ID),
    CONSTRAINT PELI_PELI_CAT_FK FOREIGN KEY (PELICULA_ID) REFERENCES PELICULAS_JMJP(PELICULA_ID),
    CONSTRAINT CAT_PELI_CAT_FK FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS_JMJP(CATEGORIA_ID)
);

CREATE TABLE PROYECCIONES_JMJP(
    PROYECCION_ID NUMBER CONSTRAINT PROYECCION_PK PRIMARY KEY,
    CINE_ID NUMBER CONSTRAINT PROYECCION_CINE_NN NOT NULL,
    PELICULA_ID NUMBER CONSTRAINT PROYECCION_PELI_NN NOT NULL,
    INICIO_PROYECCIONES DATE CONSTRAINT PRO_INICIO_NN NOT NULL,
    FIN_PROYECCIONES DATE,
    CONSTRAINT PROYECCION_CINE_FK FOREIGN KEY (CINE_ID) REFERENCES CINES_JMJP(CINE_ID),
    CONSTRAINT PROYECCION_PELICULA_FK FOREIGN KEY (PELICULA_ID) REFERENCES PELICULAS_JMJP(PELICULA_ID)
);

CREATE TABLE CLIENTES_JMJP(
    CLIENTE_ID NUMBER CONSTRAINT CLIENTE_PK PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(50) CONSTRAINT NOMBRE_CLIENTE_NN NOT NULL,
    EDAD NUMBER(2)
);

CREATE TABLE REF_PAGOS_JMJP(
    REF_PAGO_ID NUMBER CONSTRAINT REF_PAGO_PK PRIMARY KEY,
    TOTAL NUMBER(7,2) CONSTRAINT TOTAL_PAGO_NN NOT NULL,
    METODO_PAGO VARCHAR2(150)
);

CREATE TABLE SALAS_JMJP(
    SALA_ID NUMBER,
    NOMBRE_SALA CHAR(3) CONSTRAINT NOMBRE_SALA_NN NOT NULL,
    CAPACIDAD INTEGER CONSTRAINT CAPACIDAD_CINE_NN NOT NULL,
    CONSTRAINT SALA_PK PRIMARY KEY (SALA_ID)
);

CREATE TABLE FUNCIONES_JMJP(
    FUNCION_ID NUMBER CONSTRAINT FUNCION_PK PRIMARY KEY,
    INICIO_FUNCION DATE,
    FIN_FUNCION DATE
);

CREATE TABLE ENTRADAS_JMJP(
    ASIENTO CHAR(2),
    CLIENTE_ID NUMBER,
    REF_PAGO_ID NUMBER,
    SALA_ID NUMBER,
    PROYECCION_ID NUMBER,
    FUNCION_ID NUMBER,
    CONSTRAINT ENTRADA_PK PRIMARY KEY (ASIENTO,CLIENTE_ID,REF_PAGO_ID,CINE_ID,SALA_ID,PROYECCION_ID,FUNCION_ID),
    CONSTRAINT CLIENTE_ENTRADA_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES_JMJP(CLIENTE_ID),
    CONSTRAINT REF_PAGO_ENTRADA_FK FOREIGN KEY (REF_PAGO_ID) REFERENCES REF_PAGOS_JMJP(REF_PAGO_ID),
    CONSTRAINT SALA_ENTRADA_FK FOREIGN KEY (SALA_ID) REFERENCES SALAS_JMJP(SALA_ID),
    CONSTRAINT PROY_ENTRADA_FK FOREIGN KEY (PROYECCION_ID) REFERENCES PROYECCIONES_JMJP(PROYECCION_ID),
    CONSTRAINT FUNCION_ENTRADA_FK FOREIGN KEY (FUNCION_ID) REFERENCES FUNCIONES_JMJP(FUNCION_ID)
);



------------------SECUENCIAS-------------------------------
CREATE SEQUENCE CID --SECUENCIA CINES
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE CATID --SECUENCIA DE CATEGORIAS
    START WITH 10
    MAXVALUE 99
    CYCLE;
    
CREATE SEQUENCE PELID --SECUENCIA DE PELICULAS
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE PROYID --SECUENCIA DE PROYECCIONES
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE CLID --SECUENCIA DE CLIENTES
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE RPID --SECUENCIA DE REF_PAGOS
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE SALID --SECUENCIA DE SALAS
    START WITH 10
    NOMAXVALUE
    NOCYCLE;
    
CREATE SEQUENCE FUNID --SECUENCIA DE FUNCIONES
    START WITH 10
    NOMAXVALUE
    NOCYCLE;



---------------------------INDICES---------------------
--INDEX PARA CINES
CREATE INDEX CIN_NOM_IDX ON CINES_JMJP(NOMBRE_CINE);
CREATE UNIQUE INDEX CIN_GER_IDX ON CINES_JMJP(GERENTE);
CREATE UNIQUE INDEX CIN_DIR_IDX ON CINES_JMJP(DIRECCION);
--INDEX PARA CATEGORIAS
CREATE UNIQUE INDEX NOM_CAT_IDX ON CATEGORIAS_JMJP(NOMBRE_CATEGORIA);
--INDEX PARA PELICULAS
CREATE INDEX NOM_PELI_IDX ON PELICULAS_JMJP(NOMBRE_PELICULA);
CREATE INDEX CLAS_PELI_IDX ON PELICULAS_JMJP(CLASIFICACION_ID);
--INDEX PARA PELICULAS_CATEGORIAS
CREATE INDEX PELI_CAT_IDX ON PELICULA_CATEGORIAS_JMJP(PELICULA_ID,CATEGORIA_ID);
--INDEX PARA PROYECCIONES
CREATE INDEX CINE_PROY_IDX ON PROYECCIONES_JMJP(CINE_ID);
CREATE INDEX PELI_PROY_IDX ON PROYECCIONES_JMJP(PELICULA_ID);
CREATE INDEX INI_PROY_IDX ON PROYECCIONES_JMJP(INICIO_PROYECCIONES);
CREATE INDEX FIN_PROY_IDX ON PROYECCIONES_JMJP(FIN_PROYECCIONES);
--INDEX DE CLIENTES
CREATE INDEX NOM_CLI_IDX ON CLIENTES_JMJP(NOMBRE_CLIENTE);
CREATE INDEX ED_CLI_IDX ON CLIENTES_JMJP(EDAD);
--INDEX PARA REF PAGOS
CREATE INDEX TOT_PAG_IDX ON REF_PAGOS_JMJP(TOTAL);
--INDEX PARA SALAS
CREATE UNIQUE INDEX NOM_SALA_IDX ON SALAS_JMJP(NOMBRE_SALA);
CREATE INDEX CAP_SALA_IDX ON SALAS_JMJP(CAPACIDAD);
--INDEX PARA FUNCIONES
CREATE INDEX INICIO_FUN_IDX ON FUNCIONES_JMJP(INICIO_FUNCION);
CREATE INDEX FIN_FUN_IDX ON FUNCIONES_JMJP(FIN_FUNCION);
--INDEX PARA ENTRADA
CREATE INDEX CLI_ENT_IDX ON ENTRADAS_JMJP(CLIENTE_ID);
CREATE INDEX PAG_ENT_IDX ON ENTRADAS_JMJP(REF_PAGO_ID);
CREATE INDEX SAL_ENT_IDX ON ENTRADAS_JMJP(SALA_ID);
CREATE INDEX PRO_ENT_IDX ON ENTRADAS_JMJP(PROYECCION_ID);
CREATE INDEX FUN_ENT_IDX ON ENTRADAS_JMJP(FUNCION_ID);
CREATE INDEX ASI_ENT_IDX ON ENTRADAS_JMJP(ASIENTO);



--------------------------SINONIMOS----------------------
CREATE SYNONYM CIN FOR CINES_JMJP;
CREATE SYNONYM CLASIF FOR CLASIFICACIONES_JMJP;
CREATE SYNONYM CAT FOR CATEGORIAS_JMJP;
CREATE SYNONYM PELI FOR PELICULAS_JMJP;
CREATE SYNONYM PELI_CAT FOR PELICULA_CATEGORIAS_JMJP;
CREATE SYNONYM PROY FOR PROYECCIONES_JMJP;
CREATE SYNONYM CLIE FOR CLIENTES_JMJP;
CREATE SYNONYM R_PAG FOR REF_PAGOS_JMJP;
CREATE SYNONYM ENT FOR ENTRADAS_JMJP;
CREATE SYNONYM SAL FOR SALAS_JMJP;
CREATE SYNONYM FUNC FOR FUNCIONES_JMJP;

